Repository investingwolf/react-native-svg-path-gradient, pull requests merged in 2020-12, with the labels that each got.

#4 Add keywords
  package.json
Labels: chore

#3 Add shields :D
  README.md
Labels: chore

#5 Feature + Fix: Rounded Corners + Minor Tweaks
  README.md
  index.js
Labels: documentation, feature, fix

#6 Feature: Percent
  README.md
  index.js
Labels: documentation, feature

#7 Chore: Add eslint rules and fix problems
  .eslintrc.js
  .prettierrc.js
  index.js
  package-lock.json
  package.json
Labels: chore

#9 Chore: Add github lint workflow
  .github/workflows/lint.yml
Labels: chore

#8 Fix duplicate key issues
  index.js
Labels: fix

#11 Chore/host images elsewhere
  README.md
  images/heart.gif
  images/react-native-svg-path-gradient-1.png
  images/react-native-svg-path-gradient.png
Labels: chore

#12 Fix Color Interpolation
  index.js
  package-lock.json
  package.json
Labels: fix
